### ISSUE TITLE
Option to turn off colors for logging in the command-line console (useful for TDD)

### ISSUE THREAD

**Issue by torarnek** [fcomb/redux-logger#93] opened 2015-11-19 09:36 UTC
When writing tests it is useful to see the flow of actions, however, the console does not understand "'color: #4CAF50; font-weight: bold'". 

It would have been great with an option to turn of the colors.

**Comment by frantic** [comment] 2015-11-19 19:24
Duplicate of #92 ?

**Comment by theaqua** [comment] 2015-11-20 05:59
Yep.

**Closed by theaqua** 2015-11-20 05:59 UTC
